version: '3'

services:
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: ajvideira/laravel-fullcycle:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: ajvideira/nginx-fullcycle:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - '80:80'

networks:
  laranet:
    name: laranet
    driver: bridge
