version: '3'

services:
  app:
    container_name: app
    build:
      context: node
    image: node:15
    entrypoint: 'dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh '
    tty: true
    volumes:
      - ./node:/usr/src/app
    ports:
      - '3000:3000'
    networks:
      - nodenet
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet

networks:
  nodenet:
    name: nodenet
    driver: bridge
